var webSocket,messages=document.getElementById("messages"),buttons=document.getElementById("buttons"),invisible=document.getElementById("invis-container"),invisibletext=document.getElementById("answerBox"),thumbsup=document.getElementById("correctThumb"),thumbsdown=document.getElementById("incorrectThumb"),myID=-1,myScore=0,roomId=-1,isHost=!1;
function initSocket(){if(void 0===webSocket||webSocket.readyState===WebSocket.CLOSED){var a=location.origin.replace(/^http/,"ws");webSocket=new WebSocket(a);webSocket.onopen=function(a){console.log("connected.");cmd("gameConnected")};webSocket.onmessage=function(a){console.log(a.data);eval(a.data)};webSocket.onclose=function(a){}}}function openRoom(){}function closeSocket(){webSocket.close()}function startGame(){}
function buzz(){var a=document.getElementById("answerBox").value;argString=JSON.stringify({roomId:roomId,ans:a});cmd("gameBuzz",argString)}function check(a,b){console.log("x:"+a);console.log("y:"+b);argString=JSON.stringify({x:a,y:b,roomId:roomId});cmd("gameCheck",argString)}function checkIfHost(){isHost=!0}function cmd(a,b){"undefined"===typeof b?send(a+"(ws);"):send(a+"(ws,"+b+");")}function send(a){webSocket.send(a)}function invisToggle(a){}function connected(){}function gameConfirm(){}
function gameStarting(){console.log("game starting...");for(invisible.className="";buttons.firstChild;)buttons.removeChild(buttons.firstChild);document.getElementById("title").className="invisible"}
function gameAskRole(){for(;buttons.firstChild;)buttons.removeChild(buttons.firstChild);var a=document.createElement("button"),b=document.createElement("button");a.textContent="Create a new room";a.setAttribute("onClick","javascript: checkIfHost(); initRoom(); cmd('gameInitRoom');");b.setAttribute("onClick","javascript: askRoom();");b.textContent="Join a room";a.className+=" joinButton btn btn-success";b.className+=" joinButton btn btn-success";buttons.appendChild(a);buttons.appendChild(b)}
function initRoom(){for(;buttons.firstChild;)buttons.removeChild(buttons.firstChild);var a=document.createElement("p");a.textContent="Loading....";a.className+="par";messages.appendChild(a)}function displayRoomId(a){for(;buttons.firstChild;)buttons.removeChild(buttons.firstChild);for(;messages.firstChild;)messages.removeChild(messages.firstChild);var b=document.createElement("p");b.textContent="Your room ID is "+a;b.className+="par";messages.appendChild(b);roomId=a}
function askRoom(){for(;buttons.firstChild;)buttons.removeChild(buttons.firstChild);var a=document.createElement("input");a.setAttribute("type","text");a.setAttribute("id","roomInput");a.className+=" form-control";messages.appendChild(a);a=document.createElement("button");a.textContent="Join room";a.setAttribute("onClick","javascript: sendRoom();");a.className+=" joinButton btn btn-success";buttons.appendChild(a)}
function sendRoom(){var a=parseInt(document.getElementById("roomInput").value);cmd("gameJoinRoom",a)}function gameId(a){myID=parseInt(a)}function gameClientsConnected(a){for(;buttons.firstChild;)buttons.removeChild(buttons.firstChild);var b=document.createElement("p");1===parseInt(a)?b.textContent="Currently, there is "+a+" client connected.":b.textContent="Currently, there are "+a+" clients connected.";b.className+=" par";buttons.appendChild(b)}
function gamePromptStart(){var a=document.createElement("button");a.textContent="Start Game";a.setAttribute("onClick","javascript: var tmpId = getRoomId(); cmd('gameStart', tmpId);");buttons.appendChild(a)}
function gameShowBuzzer(a){console.log("Hello from the other side");isHost?(console.log(a),invisible.className="invisible",qDiv=document.getElementById("question"),qDiv.className="questionStyle",qDiv.textContent=a):(console.log(a),invisible.className="invisible",document.getElementById("answerSubmit").className="",document.getElementById("answerBox").className="")}function gameShowQuestion(){}function gameDisable(){document.getElementById("answerSubmit").disabled=!0}
function gameEnable(){document.getElementById("answerSubmit").disabled=!1}function gameCorrect(){for(var a=document.getElementById("thumbsContainer");a.firstChild;)a.removeChild(a.firstChild);var b=document.createElement("i");b.className="fa fa-thumbs-up correctSize";a.appendChild(b);document.getElementById("answerSubmit").className="invisible";document.getElementById("answerBox").className="invisible";document.getElementById("scoreTable").className="invisible row";setTimeout(function(){},2E3)}
function gameQuestionComplete(){question=document.getElementById("question");question.textContent="";for(var a=document.getElementById("thumbsContainer");a.firstChild;)a.removeChild(a.firstChild);document.getElementById("answerSubmit").className="invisible";document.getElementById("answerBox").className="invisible";document.getElementById("invis-container").className="";document.getElementById("scoreTable").className="row"}
function gameIncorrect(){var a=document.getElementById("thumbsContainer"),b=document.createElement("i");b.className="fa fa-thumbs-down correctSize";a.appendChild(b);document.getElementById("answerSubmit").className="invisible";document.getElementById("answerBox").className="invisible";document.getElementById("scoreTable").className="invisible row";setTimeout(function(){},2E3)}function gameScore(a){console.log(parseInt(a));myScore+=parseInt(a)}
function gameScoreReport(a){for(var b=0;b<Integer.parseInt(text.substring(17,18));b++){var c=document.createElement("div");c.id="c"+b;myDiv.setContent(a[b]);toAdd.appendChild(c)}document.getElementById("scoreTable").className="row"}
function roomNotFound(a){for(;buttons.firstChild;)buttons.removeChild(buttons.firstChild);for(;messages.firstChild;)messages.removeChild(messages.firstChild);var b=document.createElement("p");b.textContent="No room found for id "+a;b.className+="par";messages.appendChild(b)}function roomConnected(a){console.log(a);roomId=a}function getRoomId(){return roomId}function questionCorrect(a){console.log("QUESTION CORRECT");myScore+=a;console.log("Current score:"+myScore)}
function questionIncorrect(){console.log("answer is incorrect")};